### ISSUE TITLE
Getting device Error 

### ISSUE THREAD

**Issue by ab124585** [PennyLaneAI/pennylane-honeywell#15]
DeviceError: The analytic argument has been replaced by shots=None. Please use shots=None instead of analytic=True.

**Comment by ab124585** [comment]
using pennylane-honeywell-0.15.0
Installing collected packages: pennylane-honeywell
Successfully installed pennylane-honeywell-0.15.0

**Comment by ab124585** [comment]
this is my code dev = qml.device("honeywell.hqs", machine='HQS-LT-S1-APIVAL',wires = 5)

**Comment by glassnotes** [comment]
Hi @ab124585, what version of PennyLane are you using? The `analytic` keyword was removed from PennyLane itself in version 0.15, so if you happen to be using an earlier version, you will need to update (the current version is 0.16). Also, does the error occur immediately when you create the device with the line of code you provided?

**Comment by ab124585** [comment]
python3.7/site-packages (0.16.0)

**Comment by ab124585** [comment]
Name: PennyLane
Version: 0.16.0
Platform info:           Linux-4.14.232-177.418.amzn2.x86_64-x86_64-with-glibc2.2.5
Python version:          3.7.10
- honeywell.hqs (PennyLane-Honeywell-0.11.0)

**Comment by glassnotes** [comment]
Hi @ab124585 , thanks for the info! It looks like the Honeywell plugin just needs to be updated in your environment; the most recent version is 0.15.0. Please try

```
pip install --upgrade pennylane-honeywell
```

and let us know if you are still running into trouble.

**Comment by ab124585** [comment]
Updated - honeywell.hqs (PennyLane-Honeywell-0.15.0). Let me check if that resolved the problem

**Comment by ab124585** [comment]
it resolved the Error. I am gettign No valid api key for HQS platform found

**Comment by ab124585** [comment]
Where should I set up my HW credential? It is not clear from the docs. I am on linux container.

**Comment by ab124585** [comment]
I only see example of config.toml for IBM access but not for HW

**Comment by ab124585** [comment]
can I have example of config.toml for honeywell?

**Comment by glassnotes** [comment]
> it resolved the Error.

Great! Thanks for letting us know.

> Where should I set up my HW credential? It is not clear from the docs. I am on linux container.

Right, you will need to obtain an API key directly from Honeywell to access their devices. Once you've got that, there are three options:
 - set the environment variable `HQS_TOKEN`
 - pass the API key directly to the device upon construction using the `api_key` argument (`device = ('honeywell.hqs', api_key = "...")`
 - use the `config.toml` file. It be much the same as the Qiskit example, except it should be a `[honeywell.global]` section with the variable `api_key = "..."` set beneath.

**Comment by ab124585** [comment]
ty. Let me try

**Comment by ab124585** [comment]
Per HW they are not supporting api_key any more only id (e-mail) and pwd

**Comment by glassnotes** [comment]
> Per HW they are not supporting api_key any more only id (e-mail) and pwd

Thanks so much for bringing this to our attention! Our team will look into it :slightly_smiling_face:

**Comment by ab124585** [comment]
Thanks. Waiting for new release :)

**Comment by antalszava** [comment]
Hi @ab124585, thank you for uncovering this issue!

Short update here: we've started investigating how the new API of Honeywell will integrate with our plugin and likely a more substantial change will be required to how the PennyLane-Honeywell device handles API requests. We have ideas for going forward, it will likely just require some time to get the new features required for the new API support through the implementation and the review phases. We'll be updating this issue once the support is ready. :)

**Comment by antalszava** [comment]
Hi @ab124585, we've merged an update into the `master` branch that should help with connecting to the Honeywell service using the new API. To use this feature, after cloning the repository the `master` branch can be checked out locally and installed via `pip install -e .`. We'll include this feature in the upcoming release.

To provide credentials when connecting, the email registered with Honeywell needs to be specified. One way to specify the email is to pass it as the `user_email` to the device. Later, on the first login (and roughly every 30 days) the associated password will be asked to connect to the Honeywell service.

I'll close this issue for now, but let us know how connecting goes! :slightly_smiling_face:
